- name: Get hostname
  shell: hostname
  register: hostname

- name: Get master private ip
  get_url:
    url: http://169.254.169.254/latest/meta-data/local-ipv4
    dest: /tmp/master_private_ip
  register: master_private_ip
  when: "'vnode-0' in hostname.stdout"

- name: Read the contents of /etc/hosts
  become: yes
  command: cat /etc/hosts
  register: hosts_content

- name: Remove lines containing "vnode-0" from the hosts file
  become: yes
  replace:
    path: /etc/hosts
    regexp: '^.*vnode-0.*$'
    replace: ''

- name: Add a line to /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    line: "master_private_ip.stdout vnode-0.localdomain vnode-0"
