- name: Get hostname
  shell: hostname
  register: hostname

- name: Get username
  shell: "getent passwd 1001 | cut -d: -f1"
  register: username

- name: Check if master_host is in hostname
  set_fact:
    is_master_host: "{{ master_host in hostname.stdout }}"

- name: Check if master_host is not in hostname
  set_fact:
    is_not_master_host: "{{ not is_master_host }}"

- name: Store registered username value in a variable
  set_fact:
    user_name: "{{ username.stdout }}"

- name: Extract network CIDR from master_private_ip
  set_fact:
    network_cidr: "{{ master_private_ip.split('.')[:3] | join('.') ~ '.0/24' }}"
  when: is_master_host

- name: Add HTCondor GPG key
  become: yes
  get_url:
    url: https://research.cs.wisc.edu/htcondor/ubuntu/HTCondor-Release.gpg.key
    dest: /tmp/HTCondor-Release.gpg.key
  when: is_master_host

- name: Import HTCondor GPG key
  become: yes
  apt_key:
    data: "{{ lookup('ansible.builtin.file', '/tmp/HTCondor-Release.gpg.key') }}"
    state: present
  when: is_master_host

- name: Add HTCondor repository to sources.list
  become: yes
  blockinfile:
    path: /etc/apt/sources.list
    block: |
      deb http://research.cs.wisc.edu/htcondor/ubuntu/8.9/focal focal contrib
      deb-src http://research.cs.wisc.edu/htcondor/ubuntu/8.9/focal focal contrib
  when: is_master_host

- name: Create condor_pool user
  become: yes
  user:
    name: condor_pool
    uid: 991
  when: is_master_host

- name: Change UID of user
  become: yes
  user:
    name: "{{ user_name }}"
    uid: 99
  when: is_master_host

- name: Find files and directories owned by UID 1001
  become: yes
  shell: find / -xdev -uid 1001
  register: files_to_update
  when: is_master_host

- name: Change ownership of files and directories
  become: yes
  file:
    path: "{{ item }}"
    owner: 99
  loop: "{{ files_to_update.stdout_lines }}"
  when: is_master_host

- name: Set ownership of /data directory
  become: yes
  file:
    path: /data
    owner: "99"
    group: "1001"
    recurse: yes
  when: is_master_host

- name: Set permissions for /data directory
  become: yes
  file:
    path: /data
    mode: "g+rwxs"
    recurse: yes
  when: is_master_host

- name: Create HTCondor pool_password directory
  become: yes
  file:
    path: /etc/pwd
    state: directory
  when: is_master_host

- name: Create HTCondor pool_password file
  become: yes
  template:
    src: templates/etc/pwd/pool_password.j2
    dest: /etc/pwd/pool_password
  when: is_master_host

- name: Set file permissions on pool_password file
  become: yes
  file:
    path: /etc/pwd/pool_password
    mode: "0600"
  when: is_master_host

- name: Create HTCondor directory for the user
  become: yes
  file:
    path: "/home/{{ user_name }}/.condor"
    state: directory
  when: is_master_host

- name: Create HTCondor user pool_password file
  become: yes
  template:
    src: templates/etc/pwd/pool_password.j2
    dest: "/home/{{ user_name }}/.condor/pool_password"
  when: is_master_host

- name: Set file permissions on pool_password file
  become: yes
  file:
    path: "/home/{{ user_name }}/.condor/pool_password"
    mode: "0600"
  when: is_master_host

- name: Create HTCondor user_config file
  become: yes
  template:
    src: templates/user_config.j2
    dest: "/home/{{ user_name }}/.condor/user_config"
  when: is_master_host

- name: Set HTCondor user directory owner
  file:
    path: "/home/{{ user_name }}/.condor"
    owner: "{{ user_name }}"
    state: directory
    recurse: yes
  when: is_master_host

- name: Create HTCondor conf directory
  become: yes
  file:
    path: /etc/condor/config.d
    state: directory
  when: is_master_host

- name: Create HTCondor conf
  become: yes
  template:
    src: templates/etc/condor/config.d/01_DODAS_Custom.j2
    dest: /etc/condor/config.d/01_DODAS_Custom
  when: is_master_host
