- name: Update apt cache
  become: yes
  apt:
    update_cache: yes
  when: is_master_host

- name: Install NFS server packages
  become: yes
  apt:
    name: nfs-server
    state: present
  when: is_master_host

- name: Install condor
  become: yes
  apt:
    name: condor
    state: present
  when: is_master_host

- name: Add condor_pool to condor group
  become: yes
  user:
    name: condor_pool
    groups: condor
    append: yes
  when: is_master_host

- name: Install NFS client packages
  become: yes
  apt:
    name: nfs-client
    state: present
  when: is_not_master_host
