- name: Create NFS mountpoint
  become: yes
  file:
    path: /data
    state: directory
  when: is_not_master_host

- name: Mount NFS volume
  become: yes
  ansible.builtin.mount:
    src: "{{ master_private_ip }}:/data"
    path: /data
    fstype: nfs
    opts: "{{ nfs_mount_opts }}"
  when: is_not_master_host
