- name: Create NFS mountpoint
  become: yes
  file:
    path: /data
    state: directory
  when: is_not_master_host

- name: Install ansible-galaxy
  become: yes
  apt:
    name: ansible
    state: present
  when: is_not_master_host

- name: Ansible POSIX mount module installation
  become: yes
  shell: "ansible-galaxy collection install ansible.posix"
  when: is_not_master_host

- name: Mount NFS volume
  become: yes
  ansible.posix.mount:
    src: "{{ master_host }}:/data"
    path: /data
    opts: "{{ nfs_mount_opts }}"
    state: mounted
    fstype: nfs
  when: is_not_master_host
